source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'Books' do
    pod 'Alamofire', '~> 4.7'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'XCGLogger', '~> 6.1.0'
    pod 'IGListKit', '~> 3.0'
    pod 'Anchorage'
    pod 'Kingfisher', '~> 4.0'
    pod 'Firebase/Core'
end